

service: test-habi
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.8
  stage: dev
  profile: deploy-habi-test
  region: us-east-2
  environment: 
    SQL_HOST: ${ssm:/SQL_HOST~true}
    SQL_USER: ${ssm:/SQL_USER~true}
    SQL_PASSWORD: ${ssm:/SQL_PASSWORD~true}
    SQL_PORT: ${ssm:/SQL_PORT}
    SQL_DATABASE: ${ssm:/SQL_DATABASE}
 
    
functions:
  get_properties_with_filter:
    handler: src/functions/get_properties_with_filter.get_properties_with_filter
    memorySize: 128
    timeout: 10
    events:
      - http: 
          method: post
          path: /get_properties
plugins:
  - serverless-python-requirements

